version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable

  nginx:
    image: nginx:alpine
    container_name: nz01
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - djangonetwork
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  web:
    image: ghcr.io/karolayneamabile/docker-django-web:latest
    container_name: dz01
    depends_on:
      - db
    expose:
      - "80"
    env_file:
      - ./.envs/.django
    networks:
      - djangonetwork
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: karolayneamabile/custom-postgres:latest
    container_name: pz01
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    networks:
      - djangonetwork
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  djangonetwork:
    driver: bridge