# Generated by Django 5.2.6 on 2025-09-05 19:36

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Mediador')
    Group.objects.get_or_create(name='Diretor')

def revert_groups(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups, revert_groups),
    ]