name: Build and publish Docker images with branch name as the tagon:push:branches:- 'main'workflow_dispatch:env:REGISTRY: ghcr.ioREGISTRY_USERNAME: ${{ github.actor }}REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}IMAGE_NAME: ${{ github.repository }}jobs:build-and-push-images:runs-on: ubuntu-latestpermissions:contents: readpackages: writesteps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Install docker-compose
    run: |
      sudo curl -L "https://github.com/docker/compose/releases/download/v2.19.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
      docker-compose --version # Verifica a instalação

  - name: Extract branch and repository name
    id: repo_metadata
    shell: bash
    run: |
      # Extraindo o nome da branch e convertendo para minúsculas
      branch_name=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]')
      echo "branch_name=$branch_name" >> $GITHUB_ENV

      # Extraindo o nome do repositório e convertendo para minúsculas
      image_name=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')
      echo "image_name=$image_name" >> $GITHUB_ENV

  - name: Log in to the Container registry
    uses: docker/login-action@v1
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ env.REGISTRY_USERNAME }}
      password: ${{ env.REGISTRY_PASSWORD }}

  - name: Build and tag Docker images for web and db
    run: |
      docker-compose -f docker-django/docker-compose.yml build web
      docker tag docker-django/web:latest ${{ env.REGISTRY }}/${{ env.image_name }}-web:${{ env.branch_name }}

      docker-compose -f docker-django/docker-compose.yml build db
      docker tag docker-django/db:latest ${{ env.REGISTRY }}/${{ env.image_name }}-db:${{ env.branch_name }}

  - name: Push Docker images to the registry
    run: |
      docker push ${{ env.REGISTRY }}/${{ env.image_name }}-web:${{ env.branch_name }}
      docker push ${{ env.REGISTRY }}/${{ env.image_name }}-db:${{ env.branch_name }}
